# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run ijobs:
jobs:
  setup-stratum0:
    runs-on: local
    env:
      SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install lsb-release
          wget https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb
          sudo dpkg -i cvmfs-release-latest_all.deb
          rm -f cvmfs-release-latest_all.deb
          sudo apt-get update
          sudo apt-get install -y cvmfs cvmfs-server
          wget https://github.com/EESSI/filesystem-layer/releases/download/latest/cvmfs-config-eessi_latest_all.deb
          sudo dpkg -i cvmfs-config-eessi_latest_all.deb
          sudo apt install -y apache2 cvmfs cvmfs-server
          

      - name: Fully clean CVMFS repo
        run: |
          echo "$SUDO_PASSWORD" | sudo -S systemctl stop autofs
          echo "$SUDO_PASSWORD" | sudo -S cvmfs_server rmfs example.domain.tld || true
          echo "$SUDO_PASSWORD" | sudo -S rm -rf /etc/cvmfs/repositories.d/example.domain.tld
          echo "$SUDO_PASSWORD" | sudo -S rm -rf /var/spool/cvmfs/example.domain.tld

      - name: Creating Keys
        run: |
          mkdir -p /etc/cvmfs/keys/example.domain.tld
          echo "$SUDO_PASSWORD" | openssl genrsa -out /etc/cvmfs/keys/example.domain.tld.masterkey 4096
          echo "$SUDO_PASSWORD" | openssl rsa -in /etc/cvmfs/keys/example.domain.tld.masterkey -pubout -out /etc/cvmfs/keys/example.domain.tld.pub
          echo "$SUDO_PASSWORD" | openssl req -new -x509 -days 3650 -key /etc/cvmfs/keys/example.domain.tld.masterkey -out /etc/cvmfs/keys/example.domain.tld.crt -subj "/CN=example.domain.tld"
          echo "$SUDO_PASSWORD" | chown root:root /etc/cvmfs/keys/example.domain.tld.*
          echo "$SUDO_PASSWORD" | chmod 600 /etc/cvmfs/keys/example.domain.tld.masterkey
          echo "$SUDO_PASSWORD" | chmod 644 /etc/cvmfs/keys/example.domain.tld.pub
          echo "$SUDO_PASSWORD" | chmod 644 /etc/cvmfs/keys/example.domain.tld.crt

      - name: Create CVMFS Stratum 0 repo
        run: |
          echo "$SUDO_PASSWORD" | sudo -S cvmfs_server mkfs example.domain.tld



