name: Build Container

on:
  push:
    branches: [ main,test_gentoo_prefix ]
  workflow_dispatch:  # Allow manual triggering


jobs:
  build-container:
    runs-on: hyperion
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      #- name: Create CVMFS public key file
        #run: |
          #echo "${{ secrets.stratum0 }}" > example.domain.tld.pub

      - name: Build Docker container
        env:
          BUILDAH_ISOLATION: chroot   # <- key line
          BUILDAH_STORAGE_DRIVER: vfs # (drop if you prefer fuse‑overlayfs)
        run: |
          docker build -t gentoo-prefix-rocky8 .

      - name: Execute Docker container
        run: |
          docker run --rm -i --cap-add SYS_ADMIN --device /dev/fuse --security-opt apparmor:unconfined gentoo-prefix-rocky8

      - name: Execute Docker and run arhcspec inside container
        run: |

          docker run --rm \
            --cap-add SYS_ADMIN \
            --device /dev/fuse \
            --security-opt apparmor:unconfined \
            --tmpfs /cvmfs:exec \
            --user root \
            gentoo-prefix-rocky8 \
            bash -c 'python3 -c "import archspec.cpu; print(str(archspec.cpu.host()))"'

#      - name: Install EasyBuild
#        run: | 
#          docker run --rm \
#          --device /dev/fuse \
#          --security-opt apparmor:unconfined \
#          --tmpfs /cvmfs:exec \
#          -e USER=scicomp \
#          -e HOME=/home/scicomp \
#          -w /home/scicomp \
#          --user scicomp \
#          cvmfs-rocky8 \
#          bash -c "cd /sci-env/scripts && ls && bash install.sh"
