# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-local:
    runs-on: local
    steps:
      - uses: actions/checkout@v4
      - name: Check if I am stratum0
        run: |
          cd /cvmfs/example.domain.tld/
          if [ $? -ne 0 ];then 
          yum install -y https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm
          sudo apt install apache2 cvmfs cvmfs-server
          sudo cvmfs_server mkfs example.domain.tld
          sudo systemctl enable apache2
          sudo systemctl start apache2
          else
          echo OK; fi
      - name: Check if cvmfs is mounted
        run: |
          cd /cvmfs/example.domain.tld/
          if [ $? -eq 0 ];then echo OK; else echo NoOK; fi


  build-hyperion:
    runs-on: hyperion
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Check if I reach Stratum0
        run: |
          cvmfs_config stat -v example.domain.tld
          if [ $? -eq 0 ];then 
          I am reaching Stratum0
          else
          sudo yum install -y https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm
          sudo yum install -y cvmfs
          sudo yum install -y https://github.com/EESSI/filesystem-layer/releases/download/latest/cvmfs-config-eessi-latest.noarch.rpm
          sudo bash -c "echo 'CVMFS_CLIENT_PROFILE="single"' > /etc/cvmfs/default.local"
          sudo bash -c "echo 'CVMFS_QUOTA_LIMIT=10000' >> /etc/cvmfs/default.local" > /etc/cvmfs/example.domain.tld
          # Setup the stratum0 configuration
          sudo bash -c "echo 'CVMFS_SERVER_URL=http://158.227.172.103/cvmfs/@fqrn@' > /etc/cvmfs/example.domain.tld
          sudo bash -c "echo 'CVMFS_PUBLIC_KEY=/etc/cvmfs/keys/example.domain.tld.pub' > /etc/cvmfs/example.domain.tld
          sudo bash -c "echo 'CVMFS_HTTP_PROXY=DIRECT'
          # copy the stratum0 public key
          scp iker@158.227.172.103:/etc/cvmfs/keys/example.domain.tld.pub /tmp
          sudo cp /tmp/example.domain.tld.pub /etc/cvmfs/keys/
          sudo cvmfs_config setup
          fi
