# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run ijobs:
jobs:
  setup-stratum0:
    runs-on: local
    env:
      SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install lsb-release
          wget https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb
          sudo dpkg -i cvmfs-release-latest_all.deb
          rm -f cvmfs-release-latest_all.deb
          sudo apt-get update
          sudo apt-get install -y cvmfs cvmfs-server
          wget https://github.com/EESSI/filesystem-layer/releases/download/latest/cvmfs-config-eessi_latest_all.deb
          sudo dpkg -i cvmfs-config-eessi_latest_all.deb
          sudo apt install -y apache2 cvmfs cvmfs-server
          

      - name: Initialize repository (mkfs)
        run: |
          sudo systemctl stop autofs
          sudo systemctl disable autofs
          sudo cvmfs_server mkfs example.domain.tld
          sudo systemctl enable apache2
          sudo systemctl start apache2



