# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run ijobs:
  setup-stratum0:
    runs-on: local
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if CVMFS Stratum0 is already mounted
        id: check-mounted
        run: |
          if [ -d "/cvmfs/example.domain.tld" ] && mountpoint -q /cvmfs/example.domain.tld; then
            echo "Stratum0 already mounted."
            echo "mounted=true" >> "$GITHUB_OUTPUT"
          else
            echo "Stratum0 not mounted."
            echo "mounted=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Install and configure CVMFS Stratum0 (if not mounted)
        if: steps.check-mounted.outputs.mounted == 'false'
        run: |
          # Install prerequisites
          sudo apt-get update
          sudo apt-get install -y wget lsb-release gnupg

          # Install CVMFS release package
          wget https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm
          sudo alien --scripts cvmfs-release-latest.noarch.rpm  # convert RPM to DEB
          sudo dpkg -i cvmfs-release-latest.noarch.deb || true
          sudo apt-get update

          # Install CVMFS and server components
          sudo apt-get install -y apache2 cvmfs cvmfs-server

          # Configure the Stratum0 repository
          sudo cvmfs_server mkfs example.domain.tld <<EOF

          # Enable and start Apache
          sudo systemctl enable apache2
          sudo systemctl start apache2

      - name: Final mount check
        run: |
          if mountpoint -q /cvmfs/example.domain.tld; then
            echo "CVMFS Stratum0 is mounted."
          else
            echo "Failed to mount CVMFS Stratum0." && exit 1
          fis made up of one or more jobs that can run sequentially or in parallel
