# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run ijobs:
jobs:
  setup-stratum0:
    runs-on: local
    env:
      SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cvmfs cvmfs-server

      - name: Generate repository keys
        run: |
          sudo cvmfs_server generate_keys example.domain.tld

      - name: Initialize repository (mkfs)
        run: |
          sudo cvmfs_server mkfs example.domain.tld

      - name: Configure repository file
        run: |
          REPO_CONF="/etc/cvmfs/repositories.d/example.domain.tld.conf"
          sudo bash -c "cat > $REPO_CONF <<EOF
          CVMFS_SERVER_REPOSITORY=example.domain.tld
          CVMFS_SERVER_STRATUM=0
          CVMFS_SERVER_STORAGE=/srv/cvmfs/example.domain.tld
          CVMFS_SERVER_KEYS=/etc/cvmfs/keys/example.domain.tld
          EOF"

      - name: Create storage directory
        run: |
          sudo mkdir -p /srv/cvmfs/example.domain.tld
          sudo chown -R $(whoami):$(whoami) /srv/cvmfs/example.domain.tld

      - name: Publish initial repository
        run: |
          sudo cvmfs_server publish example.domain.tld

      - name: Start and enable CVMFS server service
        run: |
          sudo systemctl start cvmfs-server
          sudo systemctl enable cvmfs-server

      - name: Mount repository (for testing)
        run: |
          sudo mkdir -p /cvmfs/example.domain.tld
          sudo mount -t cvmfs example.domain.tld /cvmfs/example.domain.tld
