name: Build Apptainer Container

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering
    paths:
      - 'apptainer.def'
      - '.github/workflows/build-container.yml'


jobs:
  build-container:
    runs-on: hyperion
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create CVMFS public key file
        run: |
          echo "${{ secrets.stratum0 }}" > example.domain.tld.pub

      - name: Build Docker container
        env:
          BUILDAH_ISOLATION: chroot   # <- key line
          BUILDAH_STORAGE_DRIVER: vfs # (drop if you prefer fuse‑overlayfs)
        run: |
          docker build -t cvmfs-rocky8 .
          
      - name: Execute Docker container
        run: |
          docker run --rm -i --cap-add SYS_ADMIN --device /dev/fuse --security-opt apparmor:unconfined cvmfs-rocky8
          
      - name: Mount and list CVMFS repo inside container
        run: |
#          docker run --rm \
#            --cap-add SYS_ADMIN \
#            --device /dev/fuse \
#            --security-opt apparmor:unconfined \
#            --tmpfs /cvmfs:exec \\
#            --user ROOT \
#            cvmfs-rocky8 \
#            bash -c "mkdir -p /cvmfs/example.domain.tld && mount -t cvmfs example.domain.tld /cvmfs/example.domain.tld && ls /cvmfs/example.domain.tld"
          docker run --rm -it \
            --privileged \
            --device /dev/fuse \
            --security-opt apparmor:unconfined \
            cvmfs-rocky8 \
            bash
#      - name: Install EasyBuild
#        run: | 
#          docker run --rm \
#          --device /dev/fuse \
#          --security-opt apparmor:unconfined \
#          --tmpfs /cvmfs:exec \
#          -e USER=scicomp \
#          -e HOME=/home/scicomp \
#          -w /home/scicomp \
#          --user scicomp \
#          cvmfs-rocky8 \
#          bash -c "cd /sci-env/scripts && ls && bash install.sh"
