name: Build and Push Ubuntu Container

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-push:
    runs-on: local
    permissions:
      contents: read
      packages: write  # Required for GHCR push

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Ubuntu container
        run: |
          # Create build directory
          mkdir -p /home/iker/eessi/container
          cd /home/iker/eessi/container
          
          # Copy the definition file from repository
          cp $GITHUB_WORKSPACE/ubuntu.def .
          
          # Build the container
          sudo apptainer build ubuntu.sif ubuntu.def
