name: Build and Push Ubuntu Container

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-push:
    runs-on: local
    permissions:
      contents: read
      packages: write  # Required for GHCR push

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Ubuntu container
        run: |
          cd ~/eessi/actions-runner
          docker build -t eessi-ubuntu -f Dockerfile .
          docker save eessi-ubuntu -o eessi-ubuntu.tar

      - name: Verify container
        run: |
          docker load -i ~/eessi/actions-runner/eessi-ubuntu.tar
          docker run --rm eessi-ubuntu lsb_release -a
