name: Build and Push Ubuntu Container

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-push:
    runs-on: local
    permissions:
      contents: read
      packages: write  # Required for GHCR push

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Ubuntu container
        run: |
          mkdir -p ~/eessi/actions-runner
          cd ~/eessi/actions-runner
          echo "Bootstrap: docker\nFrom: ubuntu:22.04\n\n%post\n    apt-get update\n    apt-get install -y curl wget git build-essential\n" > eessi-ubuntu.def
          sudo apptainer build eessi-ubuntu.sif eessi-ubuntu.def

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: eessi-ubuntu-container
          path: ~/eessi/actions-runner/eessi-ubuntu.sif
