# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-local:
    runs-on: local
    steps:
      - uses: actions/checkout@v4
      - name: Check if I am stratum0
        run: |
          cd /cvmfs/example.domain.tld/
          if [ $? -ne 0 ];then 
          yum install -y https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm
          sudo apt install apache2 cvmfs cvmfs-server
          sudo cvmfs_server mkfs example.domain.tld
          sudo systemctl enable apache2
          sudo systemctl start apache2
          cd /cvmfs/example.domain.tld/
          if [ $? -eq 0 ];then "CVMFS repo has been mounted"
          else 
          echo "CVMFS has not been mounted"; 
          exit
          else
          echo OK; fi
      - name: Check if cvmfs is mounted
        run: |
          cd /cvmfs/example.domain.tld/
          if [ $? -eq 0 ];then echo OK; else 


  #build-hyperion:
  #  runs-on: hyperion
  #  # Steps represent a sequence of tasks that will be executed as part of the job
  #  steps:
  #    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #    - uses: actions/checkout@v4

  #    # Runs a single command using the runners shell
  #    - name: Run a one-line script
  #      run: |
  #        ebw -f Go -c cascadelake.yaml 
